version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
    - "8000:8000"
    networks:
      - tts-network

  web-ui:
    build:
      context: ./web_ui
    container_name: web_ui
    ports:
      - "8501:8501"
    depends_on:
      - api-gateway
    networks:
      - tts-network

  preprocessing-service:
    build:
      context: ./preprocessing-service
    container_name: preprocessing-service
    ports:
      - "8001:8000"
    networks:
      - tts-network
    depends_on:
      - api-gateway

networks:
  tts-network:
    driver: bridge
