version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
    - "8000:8000"
    environment:
      - PREPROCESS_URL=http://preprocessing-service:8000/preprocess
      - TTS_URL=http://tts-service:8000/synthesize
    networks:
      - tts-network
    depends_on:
      - preprocessing-service
      - tts-service

  web-ui:
    build:
      context: ./web_ui
    container_name: web_ui
    ports:
      - "8501:8501"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    networks:
      - tts-network
    depends_on:
      - api-gateway

  preprocessing-service:
    build:
      context: ./preprocessing-service
    container_name: preprocessing-service
    ports:
      - "8001:8000"
    networks:
      - tts-network

  tts-service:
    build:
      context: ./tts-service
    container_name: tts-service
    ports:
      - "8002:8000"
    networks:
      - tts-network

networks:
  tts-network:
    driver: bridge
